import React,{useEffect,useRef,useState} from 'react';
import {Link as RouterLink,NavLink as RouterNavLink,Outlet,ScrollRestoration,useLocation,useParams} from 'react-router-dom';
import {MotionProvider,MotionEffects,ImmersiveHero,ScrollStage,ModeTransition,useMotionSettings,Comparison,GestureNarrative,SoundRail} from './Motion.jsx';
import {CinematicHome} from './Cinematic.jsx';
import {ProjectMedia,ProjectVideo} from './Media.jsx';
import {media,mediaGroups,videos} from './media.mjs';
import {email,statement,selectedIntro,closing,works,caseSections,headerFor,systems,systemBody,about,background,anchor} from './data.mjs';

const Arrow=()=> <svg aria-hidden="true" viewBox="0 0 16 16" width="16" height="16"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>;
function Link(props){const {calm}=useMotionSettings();return <RouterLink {...props} viewTransition={!calm}/>;}
function NavLink(props){const {calm}=useMotionSettings();return <RouterNavLink {...props} viewTransition={!calm}/>;}
function Inline({text}){return text.split(/(\*\*.*?\*\*)/g).map((s,i)=>s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s);}
function Copy({text}){return <div className="copy">{text.split(/\n\s*\n/).filter(Boolean).map((block,i)=>block.trim().startsWith('- ')?<ul key={i}>{block.trim().split('\n').map((s,j)=><li key={j}><Inline text={s.replace(/^- /,'')}/></li>)}</ul>:<p key={i}>{block.split('\n').map((s,j)=><React.Fragment key={j}>{j>0&&<br/>}<Inline text={s}/></React.Fragment>)}</p>)}</div>;}
function MediaGroup({id,title,compact=false}){return <div className={`media-group ${compact?'compact':''}`} data-media-group={id} aria-label={title}>{mediaGroups[id].map(mediaId=><ProjectMedia key={mediaId} id={mediaId} title={media[mediaId].alt}/>)}</div>;}
function ReviewGateGallery(){
 const [active,setActive]=useState(0);
 const labels=['Overview','Candidate review','Skill Pack review'];
 const ids=mediaGroups['SYS-2-3'];
 const id=ids[active];
 return <div className="review-gate-gallery" data-media-group="SYS-2-3" aria-label="Human review gates screenshots">
  <div className="review-gate-controls" role="group" aria-label="Choose a review stage">{ids.map((mediaId,index)=><button key={mediaId} type="button" aria-pressed={active===index} onClick={()=>setActive(index)}>{String(index+1).padStart(2,'0')} · {labels[index]}</button>)}</div>
  <a className="review-gate-image" href={media[id].src} target="_blank" rel="noopener noreferrer" aria-label={`Open ${labels[active]} screenshot at full size in a new tab`}><ProjectMedia key={id} id={id} title={media[id].alt}/></a>
  <p className="review-gate-hint">Select a review stage, then open the image to inspect its original size.</p>
 </div>;
}
function Placeholder(props){return videos[props.id]?<ProjectVideo id={props.id}/>:props.id==='SYS-2-3'?<ReviewGateGallery/>:mediaGroups[props.id]?<MediaGroup id={props.id} title={props.title} compact={props.compact}/>:media[props.id]?<ProjectMedia id={props.id} title={props.title} fit={props.fit} shared={/-COVER$|-HERO$/.test(props.id)} priority={/-HERO$/.test(props.id)}/>:<FallbackPlaceholder {...props}/>;}
function FallbackPlaceholder({id,title,brief,ratio='16:9',type='IMAGE',compact=false}){return <figure className={`placeholder ${compact?'compact':''}`} data-slot={id}><div className="slot-meta"><span>{type} PLACEHOLDER</span><span>{id} · {ratio}</span></div><div className="slot-center"><svg aria-hidden="true" viewBox="0 0 48 36" width="48" height="36"><rect x="1" y="1" width="46" height="34" fill="none" stroke="currentColor"/><path d="m3 31 12-13 10 10 7-8 13 11" fill="none" stroke="currentColor"/><circle cx="33" cy="10" r="3" fill="none" stroke="currentColor"/></svg><figcaption><strong>{title}</strong><p lang="zh-CN">{brief}</p></figcaption></div><span className="slot-note">Reserved for project media</span></figure>;}
function Actions({work,film=false}){return <div className="actions">{!film&&<Link className="button" to={`/projects/${work.slug}`}>View project <Arrow/></Link>}<a className={film?'button':'text-link'} href={`/experiences/${work.slug}/index.html`} target="_blank" rel="noreferrer">Launch live work <Arrow/><span className="sr-only"> (opens in a new tab)</span></a>{film&&<a className="text-link" href="#film">Watch film ↓</a>}</div>;}
function Contact({footer=false}){const [status,setStatus]=useState('');const copy=async()=>{try{await navigator.clipboard.writeText(email);setStatus('Email copied.');}catch{setStatus('Copy is unavailable. Select the email address or use the email link.');}};return <div className={footer?'contact footer-contact':'contact'}><h2>Get in touch</h2><a className="email" href={`mailto:${email}`}>{email}<Arrow/></a><div className="contact-bottom"><button className="text-link" onClick={copy}>Copy email</button><span role="status">{status}</span><span>China</span></div></div>;}
function Layout(){const {pathname:rawPathname}=useLocation();const pathname=rawPathname.replace(/\/+$/, '')||'/';const [menu,setMenu]=useState(false);const trigger=useRef();const panel=useRef();useEffect(()=>{setMenu(false);const title=pathname.startsWith('/projects/')?works.find(w=>pathname.endsWith(w.slug))?.title:pathname==='/systems'?'Systems & Research':pathname==='/about'?'About':pathname==='/works'?'Selected Works':null;document.title=title?`${title} · Huang Zijia`:'Portfolio';},[pathname]);useEffect(()=>{if(!menu)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.querySelector('a')?.focus();const key=e=>{if(e.key==='Escape'){setMenu(false);trigger.current?.focus();}if(e.key==='Tab'){const nodes=[trigger.current,...panel.current.querySelectorAll('a')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);};},[menu]);return <><MotionEffects/><a className="skip" href="#main">Skip to main content</a><header className="site-nav"><Link className="wordmark" to="/">Portfolio</Link><button ref={trigger} className="menu-button" aria-expanded={menu} aria-controls="primary-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button><nav ref={panel} id="primary-nav" className={menu?'open':''} aria-label="Primary"><NavLink to="/works">Works</NavLink><NavLink to="/systems">Systems</NavLink><NavLink to="/about">About</NavLink><a href={`mailto:${email}`}>Email <Arrow/></a></nav></header><main id="main" tabIndex={-1}><Outlet/></main><footer><Contact footer/><div className="footer-bottom"><Link to="/">Portfolio</Link><div><Link to="/works">Works</Link><Link to="/systems">Systems</Link><Link to="/about">About</Link><a href="#main">Back to top ↑</a></div><span>© 2026</span></div></footer><ScrollRestoration/></>;}
function WorkItem({work,index}){return <article className="work-row" id={work.slug}><div><p className="meta">{String(index+1).padStart(2,'0')} / 03 · {work.tag} · 2026</p><h3><Link to={`/projects/${work.slug}`}>{work.title}</Link></h3><p className="work-line">{work.line}</p><p>{work.summary}</p><p className="meta">{work.tools}</p><Actions work={work}/></div><Placeholder id={`${work.code}-COVER`} title={`${work.title} · cover`} brief={work.cover}/></article>;}
function Home(){return <><CinematicHome/><section id="practice" className="practice section wrap"><p className="meta">My practice</p><h2>Computation as a perceptual medium.</h2><p className="lead narrow">{closing}</p><Link className="text-link" to="/about">About my practice <Arrow/></Link></section><section id="systems-preview" className="section wrap"><div className="section-head"><h2>Systems & Research</h2><Link className="text-link" to="/systems">Explore systems <Arrow/></Link></div><p className="lead narrow">The works are supported by a broader engineering practice in data analysis and explainable AI systems.</p>{systems.map((s,i)=><article className="system-preview" key={s.id}><Placeholder compact id={`HOME-SYSTEM-${i+1}`} title={`${s.title} · overview`} brief={s.slots[0][1]} ratio="16:10"/><div><h3>{s.title}</h3><p>{s.brief}</p><Link className="text-link" to={`/systems#${s.id}`}>View system <Arrow/></Link></div></article>)}</section><section id="about-preview" className="section wrap split"><h2>About</h2><div><p className="lead">{about.split('\n\n')[0]}</p><p>B.Eng. Computer Science and Technology · Yangzhou University · 2022–2026</p><Link className="text-link" to="/about">About my practice <Arrow/></Link></div></section></>;}
function Works(){return <div className="wrap"><section className="page-intro"><p className="meta">Interactive works · 2026</p><h1>Selected Works</h1><p className="lead narrow">{selectedIntro}</p><nav className="jump-links" aria-label="Works index">{works.map(w=><a href={`#${w.slug}`} key={w.slug}>{w.title} ↓</a>)}</nav></section>{works.map((w,i)=><WorkItem work={w} index={i} key={w.slug}/>)}</div>;}

function ModePicker({id,items,title,brief}){const [active,setActive]=useState(0);const panel=(i,options={})=><Placeholder id={`${id}-${i+1}`} title={`${title} · ${items[i]}`} fit={options.fit} brief={`${brief} 当前选择：${items[i]}。`} ratio="16:10"/>;const note=id==='GT-GESTURE'?'Four recorded input/result pairs, not a continuous simulation.':id==='GT-MEMORY'?'Existing Concept and Realism captures; not a synchronized state comparison.':id==='FB-MODE'?'Matched original, parameters and crop. Drag the divider or use the keyboard-accessible slider.':'The source image, cluster count and kernel width stay fixed; only fuzziness m changes.';return <div className={`mode-picker mode-${id}`}><div className="mode-position"><span>{title}</span><span>{String(active+1).padStart(2,'0')} / {String(items.length).padStart(2,'0')}</span></div>{id==='GT-GESTURE'?<GestureNarrative items={items} active={active} setActive={setActive} renderPanel={panel}/>:id==='SS-MODE'?<SoundRail items={items} active={active} setActive={setActive} renderPanel={panel}/>:<><div className="mode-controls" role="group" aria-label={title}>{items.map((name,i)=><button key={name} aria-pressed={i===active} onClick={()=>setActive(i)}>{name}</button>)}</div>{id==='FB-MODE'?<Comparison items={items} active={active} renderPanel={panel}/>:<div aria-live="polite"><ModeTransition active={active}>{panel(active)}</ModeTransition></div>}</>}{id!=='SS-MODE'&&<p className="prototype-note">{note}</p>}</div>;}
function Evidence({work,section}){const n=section.name;if(work.code==='GT'){
 if(n==='Four Gestures, Four Forces')return <ModePicker id="GT-GESTURE" title="Gesture and terrain response" items={['Open Palm','Fist','Pinch','V Sign']} brief="需要一组真实手势输入 + 对应地形结果的配对图片；同一视角、英文标签。"/>;
 if(n==='A Landscape That Remembers')return <ModePicker id="GT-MEMORY" title="One landscape, two readings" items={['Concept','Realism']} brief="需要同一地形历史、同一镜头的 Concept / Realism 截图，不使用不同生成状态。"/>;
 if(n==='Technical Notes')return <Placeholder id="GT-EVIDENCE" title="Local recognition and preliminary evaluation" brief="需要关键点、识别结果和地形响应同屏证据图，以及 12 次试验 / 658 帧的测试记录；明确单人测试限制。"/>;
 }if(work.code==='SS'){
 if(n==='Five Visual Grammars')return <ModePicker id="SS-MODE" title="Five visual readings" items={['Particle Ripple','Spectral Bloom','Nebula Flow','Paint Splash','Corridor']} brief="需要同一授权音频时间段的模式画面，保证音源和采样时间可比较，隐藏旧文件名。"/>;
 if(n==='Comparison as Interaction')return <Placeholder id="SS-CORRIDOR-ALT" title="Corridor · alternate recorded response" brief="An independently recorded variation within the Corridor mode."/>;
 if(n==='Shared Signal Architecture')return <Placeholder id="SS-SIGNAL" title="Shared signal architecture" brief="需要音频分析链路图：音源 → Web Audio → RMS / 频段 / 质心 / 节拍 → 五个视觉模块；只画真实实现。"/>;
 }if(work.code==='FB'){
 if(n==='Three Ways of Seeing')return <ModePicker id="FB-MODE" title="Classification readings" items={['Soft Blend','Hard Partition','Entropy']} brief="需要同一原图、同一参数、同一裁切的三模式结果图，确保可直接比较。"/>;
 if(n==='The Viewer Controls the Boundary')return <ModePicker id="FB-PARAM" title="Fuzziness comparison" items={['m = 1.1','m = 2.5','m = 3.5']} brief="需要固定原图、簇数量和 sigma，仅改变 m 的参数对比图。"/>;
 if(n==='From Analytical Tool to Visual Material')return <><Placeholder id="FB-ORIGIN" title="From customer memberships to image pixels" brief="需要客户分群隶属度视图与图像隶属度视图的真实并列对照，说明算法来源。"/><Link className="text-link" to="/systems#kfcm-clustering">Explore the KFCM system <Arrow/></Link></>;
 if(n==='Technical Notes')return <Placeholder id="FB-ALGORITHM" title="KFCM pipeline and membership inspection" brief="需要真实计算流程 / 像素隶属度向量截图，保留簇数、m、sigma 和收敛条件。"/>;
 }return null;}
function Project(){const {slug}=useParams();const work=works.find(w=>w.slug===slug);if(!work)return <NotFound/>;return <ProjectContent key={slug} work={work}/>;}
function ProjectContent({work}){const sections=caseSections(work.title).filter(s=>s.name!=='Project Header'&&s.name!=='Audio Credit Placeholder');const header=headerFor(work.title);const next=works[(works.indexOf(work)+1)%works.length];return <div className="wrap"><div className="breadcrumb"><Link to="/works">← Selected Works</Link><span>{work.title}</span></div><section className="project-intro"><p className="meta">{work.tag} · 2026</p><h1>{work.title}</h1><Placeholder id={`${work.code}-HERO`} title={`${work.title} · opening artwork`} brief={work.cover}/><div className="project-header-copy"><h2>{work.line}</h2><div><p className="lead">{header.intro}</p><Copy text={header.facts}/><Actions work={work} film/><p className="permission-note">{work.support}</p></div></div></section><details className="contents" open><summary>On this page</summary><nav aria-label="Project contents">{sections.map(s=><a key={s.name} href={`#${anchor(s.name)}`}>{s.name}</a>)}<a href="#film">Film</a>{work.code==='SS'&&<a href="#audio-credit">Audio</a>}</nav></details>{sections.map(section=>section.name==='Technical Notes'?<section id={anchor(section.name)} className="case-section" key={section.name}><h2>{section.name}</h2><div><p>Implementation, evaluation evidence, and the limits of the available results.</p><details className="technical"><summary>Read technical notes</summary><Copy text={section.body}/><Evidence work={work} section={section}/></details></div></section>:<section id={anchor(section.name)} className="case-section" key={section.name}><h2>{section.name}</h2><div><Copy text={section.body}/><Evidence work={work} section={section}/></div></section>)}<section id="film" className="section"><h2>{work.code==='GT'?'Interaction film':work.code==='SS'?'Visual comparison film':'Mode comparison film'}</h2><Placeholder id={`${work.code}-FILM`} type="VIDEO" title={`${work.title} · demonstration film`} brief={work.film}/></section>{work.code==='SS'&&<section id="audio-credit" className="case-section"><h2>Audio</h2><div><p>Music used in the recorded visual demonstration.</p><dl className="credit-list"><dt>Track</dt><dd>Speed of Light</dd><dt>Artist / Label</dt><dd>Monster Siren Records (塞壬唱片)</dd></dl></div></section>}<section className="next-project section"><p className="meta">Next work</p><Link to={`/projects/${next.slug}`}><h2>{next.title} <Arrow/></h2></Link><Link className="text-link" to="/works">All selected works</Link></section></div>;}
function Systems(){return <div className="wrap"><section className="page-intro"><p className="meta">Engineering practice</p><h1>Systems &<br/> Research</h1><p className="lead narrow">Selected engineering projects that support my computational arts practice through data analysis, full-stack development, and explainable AI workflows.</p><p className="prototype-note">Archived implementation captures retain their original Chinese interface; the surrounding case studies and captions are presented in English.</p><nav className="jump-links" aria-label="Systems index">{systems.map(s=><a key={s.id} href={`#${s.id}`}>{s.title} ↓</a>)}</nav></section>{systems.map((s,i)=><section id={s.id} className="system-case section" key={s.id}><h2>{s.title}</h2><Copy text={systemBody(s.title)}/><Placeholder id={`SYS-${i+1}-OVERVIEW`} title={s.slots[0][0]} brief={s.slots[0][1]}/><h3>Evidence & process</h3>{s.slots.slice(1).map(([name,brief],j)=><details className="evidence-detail" key={name}><summary>{name}</summary><p>{s.id==='kfcm-clustering'?'Inspect how the system turns transaction records into customer profiles, memberships and evaluated results.':'Inspect the source evidence, review decisions and evaluation outcomes behind the release.'}</p><Placeholder id={`SYS-${i+1}-${j+2}`} title={name} brief={brief}/></details>)}{i===0&&<Link className="text-link" to="/projects/fuzzy-boundaries">From this system to Fuzzy Boundaries <Arrow/></Link>}</section>)}</div>;}
function About(){return <div className="wrap"><section className="page-intro"><p className="meta">Huang Zijia · Creative Technologist</p><h1>About</h1></section><section className="case-section about-copy"><h2>My practice</h2><Copy text={about}/></section><section className="case-section"><h2>Selected Background</h2><Copy text={background}/></section><section className="section"><h2>Practice index</h2><Placeholder id="ABOUT-INDEX" title="Gesture / sound / uncertainty" brief="需要从三个真实作品中各取一张图，横向形成实践索引；不需要头像或外部图库照片。" ratio="3:1"/><div className="jump-links">{works.map(w=><Link key={w.slug} to={`/projects/${w.slug}`}>{w.title} <Arrow/></Link>)}</div></section></div>;}
function NotFound(){return <section className="wrap page-intro not-found"><p className="meta">404</p><h1>Page not found.</h1><p className="lead">This page is not part of the portfolio. Explore the selected works or return home.</p><div className="actions"><Link className="button" to="/works">Selected Works <Arrow/></Link><Link className="text-link" to="/">Return home</Link></div></section>;}
export const routes=[{element:<MotionProvider><Layout/></MotionProvider>,children:[{path:'/',element:<Home/>},{path:'/works',element:<Works/>},{path:'/projects/:slug',element:<Project/>},{path:'/systems',element:<Systems/>},{path:'/about',element:<About/>},{path:'*',element:<NotFound/>}]}];
