import React,{useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ImmersiveHero,useMotionSettings} from './Motion.jsx';
import {ProjectMedia} from './Media.jsx';
import {works,selectedIntro} from './data.mjs';
import {clamp} from './motion-math.mjs';
import {cinematicState} from './cinematic-math.mjs';
export function useCinemaEnabled(){const {calm}=useMotionSettings();const [wide,setWide]=useState(()=>typeof window!=='undefined'&&matchMedia('(min-width:1024px) and (min-height:700px)').matches);useEffect(()=>{const q=matchMedia('(min-width:1024px) and (min-height:700px)');const sync=()=>setWide(q.matches);sync();q.addEventListener('change',sync);return()=>q.removeEventListener('change',sync);},[]);return wide&&!calm;}
export function useScrub(ref,enabled,onFrame){const callback=useRef(onFrame);callback.current=onFrame;useEffect(()=>{if(!enabled)return;let raf=0;const update=()=>{raf=0;const r=ref.current.getBoundingClientRect();const nav=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--nav-h'));callback.current(clamp((nav-r.top)/Math.max(1,r.height-innerHeight+nav)));};const schedule=()=>{if(!raf)raf=requestAnimationFrame(update);};update();addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);return()=>{cancelAnimationFrame(raf);removeEventListener('scroll',schedule);removeEventListener('resize',schedule);};},[enabled,ref]);}
export function CinematicHome(){
 const root=useRef();const enabled=useCinemaEnabled();const {calm}=useMotionSettings();const [active,setActive]=useState(0);const [inStage,setInStage]=useState(false);
 useScrub(root,enabled,p=>{const s=cinematicState(p),el=root.current;el.style.setProperty('--hero-exit',s.hero);el.style.setProperty('--stage-entry',s.entry);el.style.setProperty('--stage-exit',s.exit);el.style.setProperty('--cinema-progress',p);el.dataset.stageVisible=s.entry>.8?'true':'false';setInStage(s.entry>.8);el.querySelectorAll('.cinema-layer').forEach((layer,i)=>layer.style.setProperty('--reveal',s.reveal[i]));setActive(n=>n===s.active?n:s.active);});
 useEffect(()=>{if(!enabled&&root.current)root.current.dataset.stageVisible='false';},[enabled]);
 function jump(i){if(enabled){const r=root.current.getBoundingClientRect();const nav=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--nav-h'));window.scrollTo({top:scrollY+r.top-nav+[.31,.56,.81][i]*(r.height-innerHeight+nav),behavior:'instant'});}else document.getElementById(works[i].slug)?.scrollIntoView({block:'start',behavior:'instant'});}
 return <div ref={root} className={`cinema-home ${enabled?'cinema-enabled':''}`}><div className="cinema-viewport"><ImmersiveHero hidden={enabled&&inStage} onExplore={enabled?e=>{e.preventDefault();jump(0);}:undefined}/><section id="selected-works" inert={enabled&&!inStage?'':undefined} aria-hidden={enabled&&!inStage?true:undefined} className="cinema-stage scroll-stage"><div className="cinema-heading"><h2>Selected Works</h2><p>{selectedIntro}</p></div><div className="cinema-toolbar"><span>Selected Works</span><nav aria-label="Jump to a work">{works.map((w,i)=><button key={w.slug} aria-label={`${String(i+1).padStart(2,'0')} ${w.title}`} aria-current={active===i?'step':undefined} onClick={()=>jump(i)}>{String(i+1).padStart(2,'0')}<span>{w.title}</span></button>)}</nav><a href="#practice" onClick={e=>{e.preventDefault();const target=document.getElementById('practice');target?.scrollIntoView({block:'start',behavior:'instant'});target?.setAttribute('tabindex','-1');target?.focus({preventScroll:true});}}>Skip stage ↓</a></div><div className="cinema-layers">{works.map((w,i)=><article id={w.slug} key={w.slug} className="cinema-layer" data-active={active===i} aria-hidden={enabled&&active!==i?true:undefined} inert={enabled&&active!==i?'':undefined} style={{zIndex:i+1}}><ProjectMedia id={`${w.code}-COVER`} title={w.title} shared={!enabled||active===i} priority/><div className="cinema-copy"><div><span className="meta">{String(i+1).padStart(2,'0')} / 03 · {w.tag}</span><h3><Link to={`/projects/${w.slug}`} viewTransition={!calm}>{w.title}</Link></h3></div><div><p>{w.line}</p><div className="actions"><Link className="button" viewTransition={!calm} to={`/projects/${w.slug}`}>View project ↗</Link><a className="text-link" href={`/experiences/${w.slug}/index.html`} target="_blank" rel="noreferrer">Launch live work ↗</a></div></div></div></article>)}</div><div className="cinema-progress" aria-hidden="true"/></section></div></div>;
}
