import content from './content.json' with { type:'json' };
export const email='741648292@qq.com';
export const statement='I build interactive works that turn gesture, sound, data, and algorithmic uncertainty into experiences people can see, shape, and question.';
export const selectedIntro='Three browser-based experiments explore computation as a perceptual medium. Each begins with a different form of input—bodily movement, an audio signal, or image data—and asks how an algorithm can make that material newly visible.';
export const closing='I am interested in what computation allows us to perceive—and what it quietly removes when it converts continuous experience into discrete output.';
export const works=[
 {slug:'gesture-terrain',title:'Gesture Terrain',code:'GT',tag:'Interactive artwork',tools:'Three.js, MediaPipe, WebGL',line:'Movement accumulates as geological memory.',summary:"Four hand gestures act as geological forces. Each movement leaves a persistent trace, allowing a virtual island to accumulate its participant's actions as terrain.",cover:'需要地形完成态大图：保留沉积、侵蚀或裂隙的空间层次，不带控制面板。',film:'需要 20–30 秒英文界面交互录像：四种手势与地形响应同屏，能看出变化的累积。',support:'Camera permission required · Desktop recommended · Video frames remain on device'},
 {slug:'shape-of-sound',title:'Shape of Sound',code:'SS',tag:'Audio-reactive generative artwork',tools:'p5.js, Web Audio API',line:'One signal, five visual readings.',summary:'One audio stream becomes five visual readings. Shared signal features are interpreted as ripples, radial blooms, flowing particles, painterly events, and a perspective corridor.',cover:'需要五模式中的代表性视觉画面：同一授权音频片段，不带播放器或文件名。',film:'需要 30–45 秒模式比较录像：同一声音片段依次对应五种视觉语法，使用已授权音频。',support:'Load audio from your device · Audio is processed locally'},
 {slug:'fuzzy-boundaries',title:'Fuzzy Boundaries',code:'FB',tag:'Interactive algorithmic image',tools:'HTML5 Canvas, KFCM',line:'What remains visible when a classifier is not forced to decide?',summary:'An image experiment that preserves the uncertainty normally erased by classification, rendering every pixel through simultaneous cluster memberships rather than one final label.',cover:'需要同一原图的 Soft Blend / Hard Partition / Entropy 三态对照图，裁切与尺寸一致。',film:'需要 20–30 秒英文界面录像：展示三态切换、参数调整和像素隶属度检查。',support:'Use a preset, upload an image, or capture a camera frame'},
];
export function caseSections(title){return content[title].split(/\n### /).slice(1).map(s=>{const [name,...rest]=s.split('\n');return {name:name.replace(/^\d+\s*—\s*/,''),body:rest.join('\n').trim().replace('single-participant study','study')};});}
export function headerFor(title){const raw=caseSections(title)[0].body;return {intro:raw.split('\n\n')[2],facts:raw.split('\n\n')[3].replace('Independent project · 5 weeks · 2026','Independent project · 2026').replace('Independent project · 3 weeks · 2026','Independent project · 2026')};}
export const systems=[
 {id:'kfcm-clustering',title:'KFCM Customer Clustering System',brief:'A full-stack graduation project that implements Kernel Fuzzy C-Means for interpretable customer segmentation. Its membership model later became the algorithmic material for Fuzzy Boundaries.',slots:[['Interface overview','需要客户分析系统总览图，显示真实输入、分析区域和结果。'],['Computation flow','需要真实计算流程图：数据清洗 → RFM 与退货率 → KFCM → 结果与报告。'],['Membership view','需要隶属度矩阵或导出视图，突出一位客户对多个簇的隶属度。'],['Comparison metrics','需要算法比较指标截图，保留标签、样本量和指标含义。']]},
 {id:'skilldistill-studio',title:'SkillDistill Studio',brief:'A full-stack AI workbench for turning long-form sources into inspectable, testable Agent Skills through provenance, human review, and failure-aware evaluation.',slots:[['Workflow overview','需要从来源导入到评估导出的工作流总览，使用真实系统截图。'],['Source anchors','需要展示候选知识与原文来源锚点对应关系的界面。'],['Human review gates','需要人工审核关卡截图，能看到批准、修改和拒绝操作。'],['Visible failures','需要评估失败用例截图，保留失败原因和低置信度标注。'],['Release decision','需要导出决策界面，明确成功项被发布、失败项被排除。']]},
];
export function systemBody(title){const raw=content['Systems & Research'];const block=raw.split('## '+title+'\n')[1]?.split('\n## ')[0]||'';return block.split('\n\n').filter(s=>s.trim()&&!s.startsWith('Suggested evidence:')).join('\n\n');}
export const about=content.About.split('\n# About\n')[1].split('\n### Selected Background')[0].trim();
export const background=content.About.split('### Selected Background\n')[1].split('### Contact')[0].trim();
export const anchor=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
